// <auto-generated />
namespace Radera.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Försökatträddalitedata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Försökatträddalitedata));
        
        string IMigrationMetadata.Id
        {
            get { return "201609150804262_Försök att rädda lite data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
